name: go_router
description: A declarative router for Flutter based on Navigation 2
version: 0.2.2
repository: https://github.com/csells/go_router

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_to_regexp: ^0.4.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
